import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { MeshoptDecoder } from 'three/examples/jsm/libs/meshopt_decoder.module.js';
import { clone } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { MerylinAnimation, MERYLIN_CLIPS, merylinGait, merylinMovementDuration, merylinPlaybackRate, merylinRouteMotion } from '../src/merylinAnimation.ts';
import { FrostmourneEffects } from '../src/frostmourneEffects.ts';
import { StingEffects } from '../src/stingEffects.ts';
import { SwordSwingRibbon } from '../src/swordSwingRibbon.ts';
import { MerylinWeapons, merylinWeaponForCard, merylinObjectSwingDeferredByChoice, randomMerylinWeapon, shuffledMerylinWeapons } from '../src/merylinWeapons.ts';
import { merylinHitDirections, merylinAttackYaw } from '../src/merylinAttackFacing.ts';
import { softenMerylinPreviewFace } from '../src/merylinPreview.ts';

const bytes = fs.readFileSync('public/models/merylin-pendragon.glb');
const jsonLength = bytes.readUInt32LE(12);
const json = JSON.parse(bytes.subarray(20, 20 + jsonLength).toString());
assert.deepEqual(json.animations.map((a: { name: string }) => a.name), [...MERYLIN_CLIPS]);
assert.equal(json.meshes.length, 2);
assert.equal(json.skins.length, 1);
assert.equal(json.skins[0].joints.length, 28);
const weaponNode = json.nodes.findIndex((node: { name?: string }) => node.name === 'Weapon_Frostmourne');
const rightHandNode = json.nodes.findIndex((node: { name?: string }) => node.name === 'RightHand');
assert.ok(weaponNode >= 0, 'Frostmourne node missing');
assert.ok(json.nodes[rightHandNode].children.includes(weaponNode), 'Frostmourne must be attached to RightHand');
for (const view of json.bufferViews) assert.ok(view.byteOffset + view.byteLength <= json.buffers[0].byteLength);
// Real GLTF parser, rig and AnimationMixer; only GPU image decoding is substituted.
const loader = new GLTFLoader();
loader.setMeshoptDecoder(MeshoptDecoder);
loader.register(() => ({ name: 'HEADLESS_TEXTURES', loadTexture: () => Promise.resolve(new THREE.Texture()) }));
const asset = await loader.parseAsync(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength), '');
assert.ok(asset.animations.every(c => c.duration > 0 && c.tracks.length > 0));
const previewFace = new THREE.Mesh(new THREE.BufferGeometry(), new THREE.MeshPhysicalMaterial({ map: new THREE.Texture() }));
previewFace.material.name = 'Merylin_Face_Hair_Soft';
previewFace.castShadow = true;
previewFace.receiveShadow = true;
const previewRoot = new THREE.Group();
previewRoot.add(previewFace);
softenMerylinPreviewFace(previewRoot);
assert.ok(previewFace.material instanceof THREE.MeshBasicMaterial, 'Menu face should use its baked texture without unstable triangle lighting');
assert.equal(previewFace.material.map !== null, true);
assert.equal(previewFace.castShadow, false);
assert.equal(previewFace.receiveShadow, false);
const softenedMaterial = previewFace.material;
softenMerylinPreviewFace(previewRoot);
assert.equal(previewFace.material, softenedMaterial, 'Menu face softening should be idempotent');
const model = clone(asset.scene);
const controller = new MerylinAnimation(model, asset.animations, () => 0);
const other = new MerylinAnimation(clone(asset.scene), asset.animations, () => 1);
assert.equal(merylinWeaponForCard('sting'),'sting');
assert.equal(merylinWeaponForCard('excalibur'),'excalibur');
assert.equal(merylinWeaponForCard('moonlight'),'moonlight');
assert.equal(merylinWeaponForCard('lightbringer'),'lightbringer');
for(const card of ['frostmourne',undefined]) assert.equal(merylinWeaponForCard(card),'frostmourne');
assert.equal(merylinObjectSwingDeferredByChoice('choosing-frostmourne','frostmourne'),true);
assert.equal(merylinObjectSwingDeferredByChoice('active','frostmourne'),false);
assert.equal(merylinObjectSwingDeferredByChoice('choosing-frostmourne','sting'),false);
assert.equal(randomMerylinWeapon(()=>0),'frostmourne');
assert.equal(randomMerylinWeapon(()=>.21),'sting');
assert.equal(randomMerylinWeapon(()=>.81),'lightbringer');
assert.deepEqual(shuffledMerylinWeapons(()=>0),['sting','excalibur','moonlight','lightbringer','frostmourne']);
const stingBytes=fs.readFileSync('public/models/sting.glb');
const stingAsset=await loader.parseAsync(stingBytes.buffer.slice(stingBytes.byteOffset,stingBytes.byteOffset+stingBytes.byteLength),'');
const stingMesh=stingAsset.scene.getObjectByName('Sting_Blade')!;
assert.ok(stingMesh instanceof THREE.Mesh);
assert.ok(!stingAsset.animations.length);
assert.equal(stingMesh.userData.sting_idle_matrix.length,16);
assert.equal(stingMesh.userData.sting_running_matrix.length,16);
assert.notDeepEqual(stingMesh.userData.sting_idle_matrix,stingMesh.userData.sting_running_matrix);
model.getObjectByName('RightHand')!.add(stingMesh);
stingMesh.name='Weapon_Sting';
const excaliburBytes=fs.readFileSync('public/models/excalibur.glb');
const excaliburAsset=await loader.parseAsync(excaliburBytes.buffer.slice(excaliburBytes.byteOffset,excaliburBytes.byteOffset+excaliburBytes.byteLength),'');
const excaliburMesh=excaliburAsset.scene.getObjectByName('Excalibur_Blade')!;
assert.ok(excaliburMesh instanceof THREE.Mesh);
assert.ok(!excaliburAsset.animations.length);
for(const key of ['excalibur_idle_matrix','excalibur_running_matrix','excalibur_attack_matrix']) assert.equal(excaliburMesh.userData[key].length,16);
assert.equal(excaliburMesh.userData.excalibur_attack_action,'Attack');
assert.equal(excaliburMesh.userData.excalibur_impact_frame,28);
model.getObjectByName('RightHand')!.add(excaliburMesh);
excaliburMesh.name='Weapon_Excalibur';
const moonlightBytes=fs.readFileSync('public/models/moonlight.glb');
const moonlightAsset=await loader.parseAsync(moonlightBytes.buffer.slice(moonlightBytes.byteOffset,moonlightBytes.byteOffset+moonlightBytes.byteLength),'');
const moonlightMesh=moonlightAsset.scene.getObjectByProperty('type','Mesh')!;
assert.ok(moonlightMesh instanceof THREE.Mesh);
assert.ok(!moonlightAsset.animations.length);
for(const key of ['moonlight_idle_matrix','moonlight_alert_matrix','moonlight_casual_matrix','moonlight_running_matrix','moonlight_attack_matrix']) assert.equal(moonlightMesh.userData[key].length,16);
assert.equal(moonlightMesh.userData.moonlight_attack_action,'Attack_Swing');
assert.equal(moonlightMesh.userData.moonlight_impact_frame,27);
model.getObjectByName('RightHand')!.add(moonlightMesh);
moonlightMesh.name='Weapon_Moonlight';
const lightbringerBytes=fs.readFileSync('public/models/lightbringer.glb');
const lightbringerAsset=await loader.parseAsync(lightbringerBytes.buffer.slice(lightbringerBytes.byteOffset,lightbringerBytes.byteOffset+lightbringerBytes.byteLength),'');
const lightbringerMesh=lightbringerAsset.scene.getObjectByName('Lightbringer_Blade')!;
assert.ok(lightbringerMesh instanceof THREE.Mesh);
assert.ok(!lightbringerAsset.animations.length);
for(const key of ['lightbringer_idle_matrix','lightbringer_alert_matrix','lightbringer_casual_matrix','lightbringer_running_matrix','lightbringer_attack_matrix']) assert.equal(lightbringerMesh.userData[key].length,16);
assert.equal(lightbringerMesh.userData.lightbringer_attack_action,'Attack');
assert.equal(lightbringerMesh.userData.lightbringer_impact_frame,28);
model.getObjectByName('RightHand')!.add(lightbringerMesh);
lightbringerMesh.name='Weapon_Lightbringer';
const hitDirections=merylinHitDirections(model,asset.animations);
for(const direction of Object.values(hitDirections)) {
  assert.ok(Number.isFinite(direction));
  for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1],[1,1]]) {
    const angle=merylinAttackYaw(dx,dz,direction);
    const strike=new THREE.Vector2(Math.sin(angle+direction),Math.cos(angle+direction));
    assert.ok(strike.distanceTo(new THREE.Vector2(dx,dz).normalize())<1e-6);
  }
}
console.log('Hit-frame yaw corrections (degrees):',Object.fromEntries(Object.entries(hitDirections).map(([k,v])=>[k,v*180/Math.PI])));
const frost=model.getObjectByName('Weapon_Frostmourne')!;
const weapons=new MerylinWeapons(frost,stingMesh,excaliburMesh,moonlightMesh,lightbringerMesh,()=>0);
weapons.update(5,false,false,'Idle',false);
assert.ok(!frost.visible && !stingMesh.visible && !excaliburMesh.visible && !moonlightMesh.visible && !lightbringerMesh.visible);
weapons.update(4.9,true,false,'Idle_Wielding',false);
assert.ok(frost.visible && !stingMesh.visible);
weapons.update(.2,true,false,'Idle_Wielding',false);
assert.ok(weapons.frostOpacity<1 && weapons.frostOpacity>0);
weapons.update(.2,true,false,'Idle_Wielding',false);
assert.ok(!frost.visible && stingMesh.visible);
weapons.update(.3,true,false,'Idle_Wielding',false);
assert.equal((stingMesh.material as THREE.Material).opacity,1);
weapons.update(5.1,true,false,'Idle_Wielding',false);
weapons.update(.4,true,false,'Idle_Wielding',false);
assert.equal(weapons.current,'excalibur','Summon shuffle includes the third sword');
assert.ok(!frost.visible && !stingMesh.visible && excaliburMesh.visible);
weapons.update(5.1,true,false,'Idle_Wielding',false);
weapons.update(.4,true,false,'Idle_Wielding',false);
assert.equal(weapons.current,'moonlight','Summon shuffle includes Moonlight');
assert.ok(!frost.visible && !stingMesh.visible && !excaliburMesh.visible && moonlightMesh.visible);
weapons.update(5.1,true,false,'Idle_Wielding',false);
weapons.update(.4,true,false,'Idle_Wielding',false);
assert.equal(weapons.current,'lightbringer','Summon shuffle includes Lightbringer');
assert.ok(!frost.visible && !stingMesh.visible && !excaliburMesh.visible && !moonlightMesh.visible && lightbringerMesh.visible);
const idlePosition=stingMesh.position.clone();
weapons.update(30,true,false,'Running',true);
assert.equal(weapons.current,'lightbringer','No automatic cycling while running');
assert.ok(stingMesh.position.distanceTo(idlePosition)>.01);
weapons.attack('frostmourne');
weapons.update(.1,false,true,'Attack_Swing',true);
assert.ok(frost.visible && !stingMesh.visible,'Attack keeps consumed summon sword visible');
weapons.attack('sting');
weapons.update(.1,false,true,'Attack_DoubleSwing',true);
assert.ok(!frost.visible && stingMesh.visible);
weapons.attack('excalibur');
weapons.update(.1,false,true,'Attack',true);
assert.ok(!frost.visible && !stingMesh.visible && excaliburMesh.visible);
assert.notDeepEqual(excaliburMesh.userData.excalibur_idle_matrix,excaliburMesh.userData.excalibur_attack_matrix);
weapons.attack('moonlight');
weapons.update(.1,false,true,'Attack_Swing',true);
assert.ok(!frost.visible && !stingMesh.visible && !excaliburMesh.visible && moonlightMesh.visible);
weapons.attack('lightbringer');
weapons.update(.1,false,true,'Attack',true);
assert.ok(!frost.visible && !stingMesh.visible && !excaliburMesh.visible && !moonlightMesh.visible && lightbringerMesh.visible);
weapons.update(.1,false,false,'Idle',false);
assert.ok(!frost.visible && !stingMesh.visible);
controller.attack('sting');
assert.equal(controller.current,'Attack_DoubleSwing');
assert.equal(controller.actions.Attack_DoubleSwing.getClip().duration,19/24);
controller.update(.249,undefined,true,false);
assert.equal(controller.hasSwingImpact,false);
controller.update(.002,undefined,true,false);
assert.equal(controller.hasSwingImpact,true,'Sting hits at source frame 7');
controller.update(1,undefined,true,false);
controller.update(.01,undefined,false,true);
assert.equal(controller.current,'Idle_Wielding');
controller.reset();
controller.attack('moonlight');
assert.equal(controller.current,'Attack_Swing');
controller.update(27/24-.001,undefined,true,false);
assert.equal(controller.hasSwingImpact,false);
controller.update(.002,undefined,true,false);
assert.equal(controller.hasSwingImpact,true,'Moonlight hits at frame 27');
controller.update(controller.actions.Attack_Swing.getClip().duration,undefined,true,false);
controller.update(.01,undefined,false,true);
assert.equal(controller.current,'Idle_Wielding');
controller.reset();
controller.attack('excalibur');
assert.equal(controller.current,'Attack');
controller.update(28/24-.001,undefined,true,false);
assert.equal(controller.hasSwingImpact,false);
controller.update(.002,undefined,true,false);
assert.equal(controller.hasSwingImpact,true,'Excalibur hits at frame 28');
controller.update(controller.actions.Attack.getClip().duration,undefined,true,false);
controller.update(.01,undefined,false,true);
assert.equal(controller.current,'Idle_Wielding');
controller.reset();
controller.attack('lightbringer');
assert.equal(controller.current,'Attack');
controller.update(28/24-.001,undefined,true,false);
assert.equal(controller.hasSwingImpact,false);
controller.update(.002,undefined,true,false);
assert.equal(controller.hasSwingImpact,true,'Lightbringer hits at frame 28');
controller.update(controller.actions.Attack.getClip().duration,undefined,true,false);
controller.update(.01,undefined,false,true);
assert.equal(controller.current,'Idle_Wielding');
controller.reset();
const exclusive = (state: MerylinAnimation) => {
  const active = Object.values(state.actions).filter(a => a.isRunning());
  assert.ok(active.length <= 1, `Overlapping actions: ${active.map(a => a.getClip().name)}`);
};
assert.equal(merylinGait(1), 'Casual_Walk'); assert.equal(merylinGait(2), 'Running'); assert.equal(merylinGait(3), 'Running');
assert.deepEqual(merylinRouteMotion([{ x: 0, z: 0 }, { x: 1, z: 0 }, { x: 1, z: 2 }], .75), { distance: 4, travelledDistance: 2 });
const timeline: Array<[number, string]> = [[0, controller.current]];
for (let i = 1; i <= 1600; i++) {
  controller.update(.05); exclusive(controller);
  if (timeline.at(-1)![1] !== controller.current) timeline.push([i * .05, controller.current]);
}
assert.ok(timeline.some(([t, name]) => name === 'Alert' && Math.abs(t - 10) < .1));
assert.ok(timeline.some(([t, name]) => name === 'Boom_Dance' && Math.abs(t - 60) < .1));
assert.equal(other.current, 'Idle', 'Cloned rigs must have independent mixers');
for (let i = 0; i < 1250; i++) { other.update(.05); exclusive(other); }
assert.equal(other.current, 'You_Groove');
const summoned = new MerylinAnimation(clone(asset.scene), asset.animations, () => 0);
summoned.update(.05, undefined, false, true);
assert.equal(summoned.current, 'Idle_Wielding');
const summonedTimeline: Array<[number, string]> = [[0, summoned.current]];
for (let i = 1; i <= 2600; i++) {
  summoned.update(.05, undefined, false, true); exclusive(summoned);
  if (summonedTimeline.at(-1)![1] !== summoned.current) summonedTimeline.push([i * .05, summoned.current]);
}
assert.ok(summonedTimeline.some(([t, name]) => name === 'Alert_Wielding' && Math.abs(t - 20) < .1));
assert.ok(!summonedTimeline.some(([, name]) => name === 'Boom_Dance' || name === 'You_Groove'));
summoned.update(.05, undefined, false, false);
assert.equal(summoned.current, 'Idle');
// Movement interrupts a dance and phase is derived from distance/time, not render cadence.
for (const squares of [1, 2, 3, 6]) {
  const durationMs = merylinMovementDuration(squares);
  const gait = merylinGait(squares);
  const movement = { squares, distance: squares * 1.92, durationMs, elapsedMs: durationMs * .4, bodyScale: 1 };
  controller.update(.016, movement); exclusive(controller);
  assert.equal(controller.current, gait);
  assert.ok(Math.abs(merylinPlaybackRate(gait, movement.distance, durationMs) - 1) < 1e-8);
  assert.ok(Math.abs(controller.actions[gait].time - (movement.elapsedMs / 1000) % controller.actions[gait].getClip().duration) < 1e-5);
  model.updateMatrixWorld(true);
  model.traverse(node => {
    if (!(node instanceof THREE.SkinnedMesh)) return;
    node.skeleton.update();
    const pos = node.geometry.getAttribute('position');
    for (let v = 0; v < pos.count; v += 37) {
      const point = node.applyBoneTransform(v, new THREE.Vector3().fromBufferAttribute(pos, v));
      assert.ok(point.toArray().every(Number.isFinite));
    }
  });
}
controller.update(.1, undefined, true, true); assert.equal(controller.current, 'Idle_Wielding');
controller.update(.1, undefined, false, true); assert.equal(controller.current, 'Idle_Wielding');
const end = controller.die(1000);
assert.ok(end > 1000);
controller.update(20); exclusive(controller);
assert.equal(controller.current, 'Dead'); assert.equal(controller.actions.Dead.paused, true);
controller.update(.1, { squares: 1, distance: 1.92, durationMs: 1000, elapsedMs: 500, bodyScale: 1 });
assert.equal(controller.current, 'Dead');
controller.reset(); assert.equal(controller.current, 'Idle');
// Box swing holds the consumed sword until the one-shot completes, then resumes ambient idle.
controller.attack();
assert.equal(controller.isAttacking, true);
controller.update(26 / 24 - .001, undefined, true, false);
assert.equal(controller.hasMoonlightRelease, false);
controller.update(.002, undefined, true, false);
assert.equal(controller.hasMoonlightRelease, true, 'Moonlight launches at frame 26');
assert.equal(controller.hasSwingImpact, false, 'Wave launches before the frame-28 direct hit');
controller.attack();
controller.update(.1, undefined, true, false);
assert.equal(controller.current, 'Attack_Swing');
assert.equal(controller.hasSwingImpact, false);
controller.update(28 / 24 - .101, undefined, true, false);
assert.equal(controller.hasSwingImpact, false, 'No hit before frame 28');
controller.update(.002, undefined, true, false);
assert.equal(controller.hasSwingImpact, true, 'Hit at frame 28');
controller.update(controller.actions.Attack_Swing.getClip().duration, undefined, true, false);
controller.update(.01, undefined, false, false);
assert.equal(controller.isAttacking, false);
assert.equal(controller.current, 'Idle');
const effectsHost = new THREE.Group();
effectsHost.add(model);
const blade = model.getObjectByName('Frostmourne_Mesh_Optimized') as THREE.Mesh;
assert.ok(blade?.isMesh);
const originalMaterial = blade.material;
const effects = new FrostmourneEffects(blade, effectsHost);
for (let i=0;i<60;i++) effects.update(i*16,true,i>20&&i<40);
assert.equal(blade.material,originalMaterial,'Effects must not replace the sword material');
for(const material of Array.isArray(blade.material) ? blade.material : [blade.material]) {
  if(!(material instanceof THREE.MeshStandardMaterial)) continue;
  const shader = {
    vertexShader: THREE.ShaderLib.standard.vertexShader,
    fragmentShader: THREE.ShaderLib.standard.fragmentShader,
    uniforms: {},
  } as Parameters<typeof material.onBeforeCompile>[0];
  material.onBeforeCompile(shader, {} as THREE.WebGLRenderer);
  assert.ok(shader.vertexShader.includes('frostBladeZ=position.z;'));
  assert.ok(shader.fragmentShader.includes('roughnessFactor=mix(roughnessFactor'));
  assert.ok(shader.fragmentShader.includes('1.0-smoothstep(0.0,0.05,frostBladeZ)'));
  assert.ok(shader.fragmentShader.includes('max(0.06,roughnessFactor*0.18)'));
  assert.ok(material.customProgramCacheKey().includes('frostmourne-polished-blade-v2'));
}
assert.ok(blade.getObjectByName('FrostmourneRunes'));
const runeMaterial=(blade.getObjectByName('FrostmourneRunes') as THREE.Mesh).material as THREE.ShaderMaterial;
assert.ok(!runeMaterial.fragmentShader.includes('float flow='), 'No ripple pattern on the blade');
const wisps: THREE.Sprite[]=[];
effectsHost.traverse(object=>{
  if(object instanceof THREE.Sprite) wisps.push(object);
  if (!(object instanceof THREE.Mesh || object instanceof THREE.Points)) return;
  const positions = object.geometry.getAttribute('position');
  assert.ok(Array.from(positions.array).every(Number.isFinite));
});
assert.equal(wisps.filter(w=>w.name.endsWith('Wisp')).length,60);
assert.equal(wisps.filter(w=>w.name.endsWith('Trail')).length,32);
assert.ok(!effectsHost.getObjectByName('SwordSwingRibbon'));
assert.ok(wisps.some(w=>w.material.opacity>0));
const wake=wisps.filter(w=>w.name.endsWith('Trail'));
effects.update(976,true,true);
assert.ok(wake.some(w=>w.material.opacity>0));
const lingering=wake.find(w=>w.material.opacity>0)!;
const worldBefore=lingering.getWorldPosition(new THREE.Vector3());
effectsHost.position.x+=.5;
effectsHost.rotation.y+=.4;
effectsHost.updateMatrixWorld(true);
effects.update(976,true,false);
assert.ok(lingering.getWorldPosition(new THREE.Vector3()).distanceTo(worldBefore)<1e-6, 'Wake stays behind in world space');
for(let t=992;t<1700;t+=16) effects.update(t,true,false);
assert.ok(wake.every(w=>w.material.opacity===0), 'Wake fades after swing');
effects.update(1000,false,false);
assert.ok(wisps.every(w=>w.material.opacity===0));
assert.equal(effectsHost.getObjectByName('FrostmourneAtmosphere')?.visible,false);
const ribbon=new SwordSwingRibbon();
ribbon.update(.02,true,true,new THREE.Vector3(),new THREE.Vector3(0,1,0));
ribbon.update(.04,true,true,new THREE.Vector3(.1,0,0),new THREE.Vector3(.1,1,0));
assert.equal(ribbon.mesh.geometry.drawRange.count,6);
ribbon.update(.3,true,false,new THREE.Vector3(),new THREE.Vector3());
assert.equal(ribbon.mesh.geometry.drawRange.count,0);
ribbon.dispose();
const stingEffects=new StingEffects(stingMesh,effectsHost);
const stingHalo=stingMesh.getObjectByName('StingBladeHalo') as THREE.Mesh<THREE.PlaneGeometry,THREE.ShaderMaterial>;
assert.ok(stingHalo);
const stingMaterial=stingMesh.material as THREE.MeshStandardMaterial;
const silverShader={vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader,uniforms:{}} as Parameters<typeof stingMaterial.onBeforeCompile>[0];
stingMaterial.onBeforeCompile(silverShader,{} as THREE.WebGLRenderer);
assert.ok(silverShader.fragmentShader.includes('1.0-smoothstep(0.22,0.30,stingBladeX)'), 'Silver finish excludes guard and grip');
assert.ok(silverShader.fragmentShader.includes('max(0.07,roughnessFactor*0.2)'));
stingEffects.update(2000,true,false);
const stingRibbon=effectsHost.getObjectByName('StingSwingRibbon') as THREE.Mesh;
assert.equal(stingRibbon.geometry.drawRange.count,0,'No ribbon while idle');
stingEffects.update(2020,true,true);
stingMesh.position.x+=.1;
stingEffects.update(2040,true,true);
assert.equal(stingRibbon.geometry.drawRange.count,6,'Saved ribbon active during Sting swings');
effectsHost.updateMatrixWorld(true);
assert.ok(stingRibbon.matrixWorld.elements.every((v,i)=>Math.abs(v-new THREE.Matrix4().elements[i])<1e-6),'Ribbon remains world-aligned');
stingEffects.update(2300,true,false);
assert.equal(stingRibbon.geometry.drawRange.count,0,'Ribbon expires after swing');
stingEffects.update(2400,false,false);
assert.equal(stingRibbon.visible,false);
assert.equal(stingHalo.material.uniforms.opacity.value,0);
stingEffects.update(2420,true,false,.4);
assert.equal(stingHalo.material.uniforms.opacity.value,.4,'Halo follows sword-change fade');
console.log(JSON.stringify({ MiB: bytes.length / 1048576, clips: asset.animations.map(c => ({ name: c.name, duration: c.duration })), timeline, checks: 'rig parsing, exclusive scheduling, both dances, movement phase, interruptions, death and revival passed' }, null, 2));
